version: 2

models:
  - name: stg_spotify_artists
    description: "Staging to prepare Spotify artists data"
    columns:
      - name: rank_position
        description: "The position of the artist in the ranking"
        data_tests:
          - not_null

      - name: artist_name
        description: "Name of the artist"
        data_tests:
          - not_null

      - name: monthly_listeners_millions
        description: "Monthly listeners in millions as of March 2026"
        data_tests:
          - not_null

      - name: primary_genre
        description: "Primary music genre of the artist"

      - name: artist_country
        description: "Country of origin of the artist"

      - name: followers_millions
        description: "Total followers in millions"

      - name: grammy_wins
        description: "Number of Grammy Awards won"

      - name: debut_year
        description: "Year the artist debuted"
        
      - name: gender
        description: "Gender of the artist"
