version: 2

models:
  - name: stg_spotify_artists
    description: "Staging to prepare Spotify artists data"
    columns:
      - name: rank_position
        description: "The position of the artist in the ranking"
        data_tests:
          - not_null

      - name: artist_name
        description: "Name of the artist"
        data_tests:
          - not_null

      - name: monthly_listeners_millions
        description: "Monthly listeners in millions as of March 2026"
        data_tests:
          - not_null

      - name: primary_genre
        description: "Primary music genre of the artist"

      - name: artist_country
        description: "Country of origin of the artist"
        data_tests:
          - not_null

      - name: followers_millions
        description: "Total followers in millions"

      - name: grammy_wins
        description: "Number of Grammy Awards won"

      - name: debut_year
        description: "Year the artist debuted"
        
      - name: gender
        description: "Gender of the artist"

  - name: stg_spotify_songs
    description: "Staging to prepare Spotify songs data"
    columns:
      - name: wrapped_2025_rank
        description: "The position of the song in the Spotify Wrapped 2025 ranking"
        data_tests:
          - not_null

      - name: song_title
        description: "Title of the song"
        data_tests:
          - not_null

      - name: artist
        description: "Main artist or artists associated with the song"
        data_tests:
          - not_null

      - name: streams_2025_billions
        description: "Total streams in 2025, in billions"

      - name: primary_genre
        description: "Primary genre classification of the song"

      - name: bpm
        description: "Song tempo in beats per minute"

      - name: duration_seconds
        description: "Duration of the song in seconds"

      - name: release_year
        description: "Year when the song was released"

      - name: artist_country
        description: "Country of origin of the artist"
        data_tests:
          - not_null

      - name: explicit
        description: "Indicates whether the song contains explicit content"

      - name: danceability
        description: "Danceability score of the song"

      - name: energy
        description: "Energy score of the song"

      - name: valence
        description: "Valence score representing musical positiveness"

      - name: acousticness
        description: "Acousticness score of the song"

      - name: peak_global_chart_position
        description: "Best global chart position reached by the song"

      - name: dataset_part
        description: "Dataset segment identifier for the Spotify Wrapped 2025 Top 50 songs"
